import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import ThemeRegistry from './ThemeRegistry'
import Sidebar from '@/components/Sidebar/Sidebar'
import { Container, Grid } from '@mui/material'
import Navbar from '@/components/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>

        <ThemeRegistry options={{ key: 'mui' }}>



          <Grid container>
            <Grid item md={2}>
              <Sidebar />
            </Grid>
            <Grid item md={10}>
              <Navbar />
              {
                children
              }
            </Grid>
          </Grid>
        </ThemeRegistry>

      </body>
    </html>
  )
}
